# Generated by Django 4.0.3 on 2022-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=600)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('industries', models.CharField(max_length=600)),
                ('employment_type', models.CharField(max_length=100)),
            ],
        ),
    ]
