# Generated by Django 4.0.3 on 2022-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
