# Generated by Django 4.0.3 on 2022-03-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
