# Generated by Django 4.0.3 on 2022-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_date_job_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_location', models.CharField(max_length=200)),
                ('app_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
