# Generated by Django 4.0.3 on 2022-03-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
