# Generated by Django 4.0.3 on 2022-03-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_applicant_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='app_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='app_location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='resume',
            new_name='Resume',
        ),
    ]
