# Generated by Django 4.0.3 on 2022-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_app_email_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.applicant'),
        ),
    ]
