# Generated by Django 4.0.3 on 2022-03-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_applicants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Resume',
            new_name='resume',
        ),
    ]
